# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'createacc.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog2(object):
    def setupUi2(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(752, 463)
        self.bgwidget = QtWidgets.QWidget(Dialog)
        self.bgwidget.setGeometry(QtCore.QRect(0, 0, 761, 471))
        self.bgwidget.setStyleSheet("QWidget#bgwidget{\n"
"background-color:qlineargradient(spread:reflect, x1:0, y1:1, x2:1, y2:0.006, stop:0 rgba(101, 152, 255, 255), stop:1 rgba(255, 255, 255, 255));}")
        self.bgwidget.setObjectName("bgwidget")
        self.label = QtWidgets.QLabel(self.bgwidget)
        self.label.setGeometry(QtCore.QRect(220, 20, 131, 51))
        self.label.setStyleSheet("font: 75 28pt \"MS Shell Dlg 2\";color:rgb(255, 255, 255)")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.bgwidget)
        self.label_2.setGeometry(QtCore.QRect(220, 80, 181, 20))
        self.label_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";color:rgb(255, 255, 255)")
        self.label_2.setObjectName("label_2")
        self.signup = QtWidgets.QPushButton(self.bgwidget)
        self.signup.setGeometry(QtCore.QRect(220, 390, 301, 41))
        self.signup.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(85, 170, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"color:rgb(255, 255, 255)\n"
"")
        self.signup.setObjectName("signup")
        self.line = QtWidgets.QFrame(self.bgwidget)
        self.line.setGeometry(QtCore.QRect(220, 70, 301, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.userfield = QtWidgets.QLineEdit(self.bgwidget)
        self.userfield.setGeometry(QtCore.QRect(220, 230, 301, 31))
        self.userfield.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.userfield.setObjectName("userfield")
        self.passwordfield = QtWidgets.QLineEdit(self.bgwidget)
        self.passwordfield.setGeometry(QtCore.QRect(220, 280, 301, 31))
        self.passwordfield.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.passwordfield.setObjectName("passwordfield")
        self.passwordfield.setEchoMode(QtWidgets.QLineEdit.Password)
        self.label_3 = QtWidgets.QLabel(self.bgwidget)
        self.label_3.setGeometry(QtCore.QRect(220, 210, 71, 20))
        self.label_3.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";color:rgb(255, 255, 255)")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.bgwidget)
        self.label_4.setGeometry(QtCore.QRect(220, 260, 71, 20))
        self.label_4.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";color:rgb(255, 255, 255)")
        self.label_4.setObjectName("label_4")
        self.error = QtWidgets.QLabel(self.bgwidget)
        self.error.setGeometry(QtCore.QRect(220, 370, 301, 16))
        self.error.setStyleSheet("color: red")
        self.error.setText("")
        self.error.setObjectName("error")
        self.confirmpasswordfield = QtWidgets.QLineEdit(self.bgwidget)
        self.confirmpasswordfield.setGeometry(QtCore.QRect(220, 330, 301, 31))
        self.confirmpasswordfield.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.confirmpasswordfield.setObjectName("confirmpasswordfield")
        self.confirmpasswordfield.setEchoMode(QtWidgets.QLineEdit.Password)
        self.label_9 = QtWidgets.QLabel(self.bgwidget)
        self.label_9.setGeometry(QtCore.QRect(220, 310, 91, 20))
        self.label_9.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";color:rgb(255, 255, 255)")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.bgwidget)
        self.label_10.setGeometry(QtCore.QRect(220, 110, 71, 20))
        self.label_10.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";color:rgb(255, 255, 255)")
        self.label_10.setObjectName("label_10")
        self.firstnamefield = QtWidgets.QLineEdit(self.bgwidget)
        self.firstnamefield.setGeometry(QtCore.QRect(220, 130, 141, 31))
        self.firstnamefield.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.firstnamefield.setObjectName("firstnamefield")
        self.label_11 = QtWidgets.QLabel(self.bgwidget)
        self.label_11.setGeometry(QtCore.QRect(370, 110, 71, 20))
        self.label_11.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";color:rgb(255, 255, 255)")
        self.label_11.setObjectName("label_11")
        self.lastnamefield = QtWidgets.QLineEdit(self.bgwidget)
        self.lastnamefield.setGeometry(QtCore.QRect(370, 130, 151, 31))
        self.lastnamefield.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.lastnamefield.setObjectName("lastnamefield")
        self.idnofield = QtWidgets.QLineEdit(self.bgwidget)
        self.idnofield.setGeometry(QtCore.QRect(220, 180, 141, 31))
        self.idnofield.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.idnofield.setObjectName("idnofield")
        self.label_19 = QtWidgets.QLabel(self.bgwidget)
        self.label_19.setGeometry(QtCore.QRect(370, 160, 71, 20))
        self.label_19.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";color:rgb(255, 255, 255)")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.bgwidget)
        self.label_20.setGeometry(QtCore.QRect(220, 160, 71, 20))
        self.label_20.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";color:rgb(255, 255, 255)")
        self.label_20.setObjectName("label_20")
        self.genderbox = QtWidgets.QComboBox(self.bgwidget)
        self.genderbox.setGeometry(QtCore.QRect(370, 180, 151, 31))
        self.genderbox.setObjectName("genderbox")
        self.genderbox.addItem("")
        self.genderbox.addItem("")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Sign Up"))
        self.label_2.setText(_translate("Dialog", "Create a brand new account."))
        self.signup.setText(_translate("Dialog", "Sign Up"))
        self.label_3.setText(_translate("Dialog", "Username:"))
        self.label_4.setText(_translate("Dialog", "Password:"))
        self.label_9.setText(_translate("Dialog", "Confrim Password:"))
        self.label_10.setText(_translate("Dialog", "First Name:"))
        self.label_11.setText(_translate("Dialog", "Last Name:"))
        self.label_19.setText(_translate("Dialog", "Gender:"))
        self.label_20.setText(_translate("Dialog", "ID No."))
        self.genderbox.setItemText(0, _translate("Dialog", "Male"))
        self.genderbox.setItemText(1, _translate("Dialog", "Female"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog2()
    ui.setupUi2(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
