# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(752, 463)
        self.bgwidget = QtWidgets.QWidget(Dialog)
        self.bgwidget.setGeometry(QtCore.QRect(0, 0, 761, 471))
        self.bgwidget.setStyleSheet("QWidget#bgwidget{\n"
"background-color:qlineargradient(spread:reflect, x1:0, y1:1, x2:1, y2:0.006, stop:0 rgba(101, 152, 255, 255), stop:1 rgba(255, 255, 255, 255));}")
        self.bgwidget.setObjectName("bgwidget")
        self.label = QtWidgets.QLabel(self.bgwidget)
        self.label.setGeometry(QtCore.QRect(220, 80, 101, 51))
        self.label.setStyleSheet("font: 75 28pt \"MS Shell Dlg 2\";color:rgb(255, 255, 255)")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.bgwidget)
        self.label_2.setGeometry(QtCore.QRect(220, 140, 181, 20))
        self.label_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";color:rgb(255, 255, 255)")
        self.label_2.setObjectName("label_2")
        self.login = QtWidgets.QPushButton(self.bgwidget)
        self.login.setGeometry(QtCore.QRect(220, 320, 301, 41))
        self.login.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(85, 170, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"color:rgb(255, 255, 255)\n"
"")
        self.login.setObjectName("login")
        self.line = QtWidgets.QFrame(self.bgwidget)
        self.line.setGeometry(QtCore.QRect(220, 130, 301, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.username = QtWidgets.QLineEdit(self.bgwidget)
        self.username.setGeometry(QtCore.QRect(220, 190, 301, 31))
        self.username.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(self.bgwidget)
        self.password.setGeometry(QtCore.QRect(220, 250, 301, 31))
        self.password.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.password.setObjectName("password")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.label_3 = QtWidgets.QLabel(self.bgwidget)
        self.label_3.setGeometry(QtCore.QRect(220, 170, 71, 20))
        self.label_3.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";color:rgb(255, 255, 255)")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.bgwidget)
        self.label_4.setGeometry(QtCore.QRect(220, 230, 71, 20))
        self.label_4.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";color:rgb(255, 255, 255)")
        self.label_4.setObjectName("label_4")
        self.error = QtWidgets.QLabel(self.bgwidget)
        self.error.setGeometry(QtCore.QRect(220, 290, 301, 16))
        self.error.setStyleSheet("color: red")
        self.error.setText("")
        self.error.setObjectName("error")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Login:"))
        self.label_2.setText(_translate("Dialog", "Login to your existing account"))
        self.login.setText(_translate("Dialog", "Login"))
        self.label_3.setText(_translate("Dialog", "Username:"))
        self.label_4.setText(_translate("Dialog", "Password:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
