from PyQt5 import QtCore, QtGui, QtWidgets
class DateEdit(QtWidgets.QDateEdit):
    def __init__(self, parent=None):
        super().__init__(parent, calendarPopup=True)
        self._today_button = QtWidgets.QPushButton(self.tr("Today"))
        self._today_button.clicked.connect(self._update_today)
        self.calendarWidget().layout().addWidget(self._today_button)

    @QtCore.pyqtSlot()
    def _update_today(self):
        self._today_button.clearFocus()
        today = QtCore.QDate.currentDate()
        self.calendarWidget().setSelectedDate(today)


class Ui_create_class(object):
    def setupUi(self, create_class):
        create_class.setObjectName("create_class")
        create_class.resize(513, 315)
        create_class.setMinimumSize(QtCore.QSize(0, 0))
        create_class.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(create_class)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(290, 75, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.course_confirm_password = QtWidgets.QLineEdit(self.frame)
        self.course_confirm_password.setGeometry(QtCore.QRect(290, 275, 201, 31))
        self.course_confirm_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.course_confirm_password.setObjectName("course_confirm_password")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(30, 160, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.course_code = QtWidgets.QLineEdit(self.frame)
        self.course_code.setGeometry(QtCore.QRect(290, 100, 201, 31))
        self.course_code.setObjectName("course_code")
        self.course_add_pass_btn = QtWidgets.QPushButton(self.frame)
        self.course_add_pass_btn.setGeometry(QtCore.QRect(330, 180, 111, 31))
        self.course_add_pass_btn.setObjectName("course_add_pass_btn")
        self.course_expire_time = QtWidgets.QTimeEdit(self.frame)
        self.course_expire_time.setGeometry(QtCore.QRect(140, 190, 101, 22))
        self.course_expire_time.setObjectName("course_expire_time")
        self.course_expire_date = DateEdit(self.frame)
        self.course_expire_date.setGeometry(QtCore.QRect(30, 190, 101, 21))
        self.course_expire_date.setObjectName("course_expire_date")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 0, 321, 61))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(30, 250, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.course_password = QtWidgets.QLineEdit(self.frame)
        self.course_password.setGeometry(QtCore.QRect(30, 275, 201, 31))
        self.course_password.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.course_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.course_password.setObjectName("course_password")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(290, 250, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(30, 75, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.course_name = QtWidgets.QLineEdit(self.frame)
        self.course_name.setGeometry(QtCore.QRect(30, 100, 201, 31))
        self.course_name.setObjectName("course_name")
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 20, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_course = QtWidgets.QPushButton(self.frame_2)
        self.add_course.setMinimumSize(QtCore.QSize(240, 50))
        self.add_course.setObjectName("add_course")
        self.horizontalLayout.addWidget(self.add_course)
        self.verticalLayout.addWidget(self.frame_2, 0, QtCore.Qt.AlignRight)
        create_class.setCentralWidget(self.centralwidget)

        self.retranslateUi(create_class)
        QtCore.QMetaObject.connectSlotsByName(create_class)

    def retranslateUi(self, create_class):
        _translate = QtCore.QCoreApplication.translate
        create_class.setWindowTitle(_translate("create_class", "MainWindow"))
        self.label_4.setText(_translate("create_class", "Subject Code"))
        self.label_3.setText(_translate("create_class", "Subject Expire Date and Time"))
        self.course_add_pass_btn.setText(_translate("create_class", "Add Password"))
        self.label.setText(_translate("create_class", "Create Class"))
        self.label_5.setText(_translate("create_class", "Add Password"))
        self.label_6.setText(_translate("create_class", "Confirm Password"))
        self.label_2.setText(_translate("create_class", "Subject Name"))
        self.add_course.setText(_translate("create_class", "Add Class"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    create_class = QtWidgets.QMainWindow()
    ui = Ui_create_class()
    ui.setupUi(create_class)
    create_class.show()
    sys.exit(app.exec_())
