# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_class.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
class DateEdit(QtWidgets.QDateEdit):
    def __init__(self, parent=None):
        super().__init__(parent, calendarPopup=True)
        self._today_button = QtWidgets.QPushButton(self.tr("Today"))
        self._today_button.clicked.connect(self._update_today)
        self.calendarWidget().layout().addWidget(self._today_button)

    @QtCore.pyqtSlot()
    def _update_today(self):
        self._today_button.clearFocus()
        today = QtCore.QDate.currentDate()
        self.calendarWidget().setSelectedDate(today)

class Ui_create_class(object):
    def setupUi(self, create_class):
        create_class.setObjectName("create_class")
        create_class.resize(526, 299)
        self.centralwidget = QtWidgets.QWidget(create_class)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 321, 61))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.course_name = QtWidgets.QLineEdit(self.centralwidget)
        self.course_name.setGeometry(QtCore.QRect(30, 90, 201, 31))
        self.course_name.setObjectName("course_name")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 65, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.course_code = QtWidgets.QLineEdit(self.centralwidget)
        self.course_code.setGeometry(QtCore.QRect(290, 90, 201, 31))
        self.course_code.setObjectName("course_code")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(290, 65, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.course_expire_date = DateEdit(self.centralwidget)
        self.course_expire_date.setGeometry(QtCore.QRect(30, 170, 101, 21))
        self.course_expire_date.setObjectName("course_expire_date")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 140, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.course_expire_time = QtWidgets.QTimeEdit(self.centralwidget)
        self.course_expire_time.setGeometry(QtCore.QRect(140, 170, 101, 22))
        self.course_expire_time.setObjectName("course_expire_time")
        self.add_course = QtWidgets.QPushButton(self.centralwidget)
        self.add_course.setGeometry(QtCore.QRect(260, 220, 231, 51))
        self.add_course.setObjectName("add_course")
        create_class.setCentralWidget(self.centralwidget)

        self.retranslateUi(create_class)
        QtCore.QMetaObject.connectSlotsByName(create_class)

    def retranslateUi(self, create_class):
        _translate = QtCore.QCoreApplication.translate
        create_class.setWindowTitle(_translate("create_class", "MainWindow"))
        self.label.setText(_translate("create_class", "Create Class"))
        self.label_2.setText(_translate("create_class", "Course Name"))
        self.label_4.setText(_translate("create_class", "Course Code"))
        self.label_3.setText(_translate("create_class", "Course Expire Date and Time"))
        self.add_course.setText(_translate("create_class", "Add Class"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    create_class = QtWidgets.QMainWindow()
    ui = Ui_create_class()
    ui.setupUi(create_class)
    create_class.show()
    sys.exit(app.exec_())
