# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'subj_password.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_subject_pass_window(object):
    def setupUi(self, subject_pass_window):
        subject_pass_window.setObjectName("subject_pass_window")
        subject_pass_window.resize(481, 228)
        self.centralwidget = QtWidgets.QWidget(subject_pass_window)
        self.centralwidget.setObjectName("centralwidget")
        self.top_course_name = QtWidgets.QLabel(self.centralwidget)
        self.top_course_name.setGeometry(QtCore.QRect(10, -10, 551, 71))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.top_course_name.setFont(font)
        self.top_course_name.setObjectName("top_course_name")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 40, 381, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.subject_pass = QtWidgets.QLineEdit(self.centralwidget)
        self.subject_pass.setGeometry(QtCore.QRect(100, 110, 281, 31))
        self.subject_pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.subject_pass.setObjectName("subject_pass")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 80, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.submit_pass_btn = QtWidgets.QPushButton(self.centralwidget)
        self.submit_pass_btn.setGeometry(QtCore.QRect(190, 160, 111, 31))
        self.submit_pass_btn.setObjectName("submit_pass_btn")
        subject_pass_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(subject_pass_window)
        QtCore.QMetaObject.connectSlotsByName(subject_pass_window)

    def retranslateUi(self, subject_pass_window):
        _translate = QtCore.QCoreApplication.translate
        subject_pass_window.setWindowTitle(_translate("subject_pass_window", "MainWindow"))
        self.top_course_name.setText(_translate("subject_pass_window", "Course Name"))
        self.label.setText(_translate("subject_pass_window", "is protected with a password, enter password to attend class"))
        self.label_2.setText(_translate("subject_pass_window", "Password"))
        self.submit_pass_btn.setText(_translate("subject_pass_window", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    subject_pass_window = QtWidgets.QMainWindow()
    ui = Ui_subject_pass_window()
    ui.setupUi(subject_pass_window)
    subject_pass_window.show()
    sys.exit(app.exec_())
