# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view_class.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
class DateEdit(QtWidgets.QDateEdit):
    def __init__(self, parent=None):
        super().__init__(parent, calendarPopup=True)
        self._today_button = QtWidgets.QPushButton(self.tr("Today"))
        self._today_button.clicked.connect(self._update_today)
        self.calendarWidget().layout().addWidget(self._today_button)

    @QtCore.pyqtSlot()
    def _update_today(self):
        self._today_button.clearFocus()
        today = QtCore.QDate.currentDate()
        self.calendarWidget().setSelectedDate(today)

class Ui_view_class(object):
    def setupUi(self, view_class):
        view_class.setObjectName("view_class")
        view_class.resize(551, 352)
        self.centralwidget = QtWidgets.QWidget(view_class)
        self.centralwidget.setObjectName("centralwidget")
        self.top_course_code = QtWidgets.QLabel(self.centralwidget)
        self.top_course_code.setGeometry(QtCore.QRect(10, -10, 551, 71))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.top_course_code.setFont(font)
        self.top_course_code.setObjectName("top_course_code")
        self.top_course_name = QtWidgets.QLabel(self.centralwidget)
        self.top_course_name.setGeometry(QtCore.QRect(30, 30, 551, 71))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.top_course_name.setFont(font)
        self.top_course_name.setObjectName("top_course_name")
        self.update_course_code = QtWidgets.QLineEdit(self.centralwidget)
        self.update_course_code.setGeometry(QtCore.QRect(310, 130, 201, 31))
        self.update_course_code.setObjectName("update_course_code")
        self.update_course_name = QtWidgets.QLineEdit(self.centralwidget)
        self.update_course_name.setGeometry(QtCore.QRect(40, 130, 201, 31))
        self.update_course_name.setObjectName("update_course_name")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 180, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.update_course_expire_time = QtWidgets.QTimeEdit(self.centralwidget)
        self.update_course_expire_time.setGeometry(QtCore.QRect(150, 210, 101, 22))
        self.update_course_expire_time.setObjectName("update_course_expire_time")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(310, 105, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 105, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.update_course = QtWidgets.QPushButton(self.centralwidget)
        self.update_course.setGeometry(QtCore.QRect(60, 270, 161, 51))
        self.update_course.setObjectName("update_course")
        self.update_course_expire_date = DateEdit(self.centralwidget)
        self.update_course_expire_date.setGeometry(QtCore.QRect(40, 210, 101, 21))
        self.update_course_expire_date.setObjectName("update_course_expire_date")
        self.delete_course = QtWidgets.QPushButton(self.centralwidget)
        self.delete_course.setGeometry(QtCore.QRect(330, 270, 161, 51))
        self.delete_course.setObjectName("delete_course")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(310, 180, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.course_status = QtWidgets.QLabel(self.centralwidget)
        self.course_status.setGeometry(QtCore.QRect(320, 200, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.course_status.setFont(font)
        self.course_status.setStyleSheet("*{\n"
"    color:rgb(0, 170, 0);\n"
"}")
        self.course_status.setAlignment(QtCore.Qt.AlignCenter)
        self.course_status.setObjectName("course_status")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(40, 80, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("*{\n"
"    color:rgb(120, 120, 135);\n"
"}")
        self.label_7.setObjectName("label_7")
        self.course_created_on = QtWidgets.QLabel(self.centralwidget)
        self.course_created_on.setGeometry(QtCore.QRect(110, 80, 191, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.course_created_on.setFont(font)
        self.course_created_on.setStyleSheet("*{\n"
"    color:rgb(120, 120, 135);\n"
"}")
        self.course_created_on.setObjectName("course_created_on")
        self.course_updated_on = QtWidgets.QLabel(self.centralwidget)
        self.course_updated_on.setGeometry(QtCore.QRect(410, 80, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.course_updated_on.setFont(font)
        self.course_updated_on.setStyleSheet("*{\n"
"    color:rgb(120, 120, 135);\n"
"}")
        self.course_updated_on.setObjectName("course_updated_on")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(310, 80, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("*{\n"
"    color:rgb(120, 120, 135);\n"
"}")
        self.label_10.setObjectName("label_10")
        view_class.setCentralWidget(self.centralwidget)

        self.retranslateUi(view_class)
        QtCore.QMetaObject.connectSlotsByName(view_class)

    def retranslateUi(self, view_class):
        _translate = QtCore.QCoreApplication.translate
        view_class.setWindowTitle(_translate("view_class", "MainWindow"))
        self.top_course_code.setText(_translate("view_class", "Course Code"))
        self.top_course_name.setText(_translate("view_class", "Course Name"))
        self.label_3.setText(_translate("view_class", "Course Expire Date and Time"))
        self.label_4.setText(_translate("view_class", "Course Code"))
        self.label_5.setText(_translate("view_class", "Course Name"))
        self.update_course.setText(_translate("view_class", "Update"))
        self.delete_course.setText(_translate("view_class", "Delete"))
        self.label_6.setText(_translate("view_class", "Status"))
        self.course_status.setText(_translate("view_class", "ACTIVE"))
        self.label_7.setText(_translate("view_class", "Created on:"))
        self.course_created_on.setText(_translate("view_class", "Created on:"))
        self.course_updated_on.setText(_translate("view_class", "Created on:"))
        self.label_10.setText(_translate("view_class", "Last Updated on:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    view_class = QtWidgets.QMainWindow()
    ui = Ui_view_class()
    ui.setupUi(view_class)
    view_class.show()
    sys.exit(app.exec_())
