# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view_records.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_view_records(object):
    def setupUi(self, view_records):
        view_records.setObjectName("view_records")
        view_records.resize(754, 398)
        view_records.setMinimumSize(QtCore.QSize(754, 398))

        self.centralwidget = QtWidgets.QWidget(view_records)
        self.centralwidget.setObjectName("centralwidget")
        self.class_attendance = QtWidgets.QTreeWidget(self.centralwidget)
        self.class_attendance.setGeometry(QtCore.QRect(10, 30, 731, 291))
        self.class_attendance.setObjectName("class_attendance")
        self.class_attendance.headerItem().setTextAlignment(0, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.class_attendance.headerItem().setFont(0, font)
        self.class_attendance.headerItem().setTextAlignment(1, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.class_attendance.headerItem().setFont(1, font)
        self.class_attendance.headerItem().setTextAlignment(2, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.class_attendance.headerItem().setFont(2, font)
        self.class_attendance.headerItem().setTextAlignment(3, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.class_attendance.headerItem().setFont(3, font)
        self.class_attendance.headerItem().setTextAlignment(4, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.class_attendance.headerItem().setFont(4, font)
        self.class_attendance.headerItem().setTextAlignment(5, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.class_attendance.headerItem().setFont(5, font)
        self.class_attendance.headerItem().setTextAlignment(6, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.class_attendance.headerItem().setFont(6, font)
        self.class_attendance.headerItem().setTextAlignment(7, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.class_attendance.headerItem().setFont(7, font)
        view_records.setCentralWidget(self.centralwidget)

        self.retranslateUi(view_records)
        QtCore.QMetaObject.connectSlotsByName(view_records)

    def retranslateUi(self, view_records):
        _translate = QtCore.QCoreApplication.translate
        view_records.setWindowTitle(_translate("view_records", "View All Attendance Records"))
        self.class_attendance.headerItem().setText(0, _translate("view_records", "Student I.D Number"))
        self.class_attendance.headerItem().setText(1, _translate("view_records", "First Name"))
        self.class_attendance.headerItem().setText(2, _translate("view_records", "Last Name"))
        self.class_attendance.headerItem().setText(3, _translate("view_records", "Subject Name"))
        self.class_attendance.headerItem().setText(4, _translate("view_records", "Subject Code"))
        self.class_attendance.headerItem().setText(5, _translate("view_records", "Subject Status"))
        self.class_attendance.headerItem().setText(6, _translate("view_records", "Time Attended"))
        self.class_attendance.headerItem().setText(7, _translate("view_records", "Status"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    view_records = QtWidgets.QMainWindow()
    ui = Ui_view_records()
    ui.setupUi(view_records)
    view_records.show()
    sys.exit(app.exec_())
